insert into ACTIVIDAD (ACTIVIDAD_PROD, ACTIVIDAD_PROD_DESC) values (1, 'Pesca');
insert into ACTIVIDAD (ACTIVIDAD_PROD, ACTIVIDAD_PROD_DESC) values (2, 'Caza');
insert into ACTIVIDAD (ACTIVIDAD_PROD, ACTIVIDAD_PROD_DESC) values (3, 'GANADERIA');
insert into ACTIVIDAD (ACTIVIDAD_PROD, ACTIVIDAD_PROD_DESC) values (4, 'CUIDADO DE TIERRAS');
insert into ACTIVIDAD (ACTIVIDAD_PROD, ACTIVIDAD_PROD_DESC) values (5, 'TOMATES');
